package controller.events;

import controller.Node;

/**
 * This class represents the events generated by adding a new dependency relation to the graph
 * @author Saba Alimadadi
 */
public class AddDependencyEvent extends DepGraphEvent {
    /** ID of add dependency */
    private static final int id = 2;
    /** The command for this event */
    private static final String command = "AddDependencyEvent";
    /** The two nodes involved in the dependency relation */
    private Node dependentNode, dependedOnNode;
    /**
     * @param source The object on which the Event initially occurred.
     * @throws IllegalArgumentException if source is null.
     */
    public AddDependencyEvent(Object source, Node dependentNode, Node dependedOnNode) {
        super(source, id, command);
        this.dependentNode = dependentNode;
        this.dependedOnNode = dependedOnNode;
    }
}
